### ISSUE TITLE
Unable to install tensorflow-riemopt using pip

### ISSUE THREAD

**Issue by thkarag** [master/tensorflow-riemopt#5]
I am trying to install tensorflow-riemopt using pip, but I get the following error:

Collecting tensorflow-riemopt
  Using cached tensorflow-riemopt-0.1.0.tar.gz (26 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_11t6hkx/tensorflow-riemopt_fac0a1b208494368aed81d89896d0ee5/setup.py", line 13, in <module>
          install_requires=Path("requirements.txt").read_text().splitlines(),
        File "/usr/lib/python3.8/pathlib.py", line 1236, in read_text
          with self.open(mode='r', encoding=encoding, errors=errors) as f:
        File "/usr/lib/python3.8/pathlib.py", line 1222, in open
          return io.open(self, mode, buffering, encoding, errors, newline,
        File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
          return self._accessor.open(self, flags, mode)
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

The installation fails. Any ideas how to fix it ? I use python 3.8 and python 3.10 and Tensorflow 2.9.

**Comment by master** [comment]
Are you installing the package from PyPi or from a local copy?

**Comment by thkarag** [comment]
I tried to install it using pip install.

**Comment by master** [comment]
Fixed in the new release.
